# Generated by Django 3.2.2 on 2021-08-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_class',
            new_name='type',
        ),
    ]
